### PR TITLE
Feature/1 single use

### LINKED ISSUE #1: I'd like my links to be single-use
When a link is created, it can be used over and over.
Would it be possible to disable a link after it’s been used once?

### PR DESCRIPTION
**Pull request by Yonggiee**
Edit  `url_mapping` schema and insertUrlMapping func definition for url single use

closes #1

### CODE REVIEW

**Comment by alloy2048** [comment]
could you let me know when it's working.

**Comment by Yonggiee** [comment]
@alloy2048 , I have sent you an email

**Comment by alloy2048** [comment]
@Yonggiee awesome, I can see that the URLs can only be decoded once.
Good stuff 👍 
It looks like the NGINX isn't handling the redirect correctly, though.

**Comment by Yonggiee** [comment]
@alloy2048 I ssh into the EC2 instance to configure the nginx.conf. The reason is because it will look for the html file for that URL. I added the nginx.conf file in the docker image to solve that.

**Comment by alloy2048** [comment]
Great job, looks like everything's working. Go ahead and close this PR.

**Pull request closed without merging**
